import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import Modal from "../components/Modal";
import Projects from "../data/data";
import Project from "../components/Project";
import Container from "../components/Container";
import Header from '../components/Header'
import Image from "next/image";
export default function Home({}) {



  return (
    <Container displayFooter={true}>

    <Head>
        <title>Holt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    
    

    <div className="grid grid-cols-2 gap-5 static">

    <div className="col-start-1 items-stretch content-center justify-self-left">
      <h1 className="text-2xl font-semi-bold">
        <Image  
        className='self-center w-5 h-5 rounded-full mx-1'
        src='/mac.png'
        alt="profilepic"
        width={20}
        height={20}
        layout="intrinsic"
        /> Holt.</h1>

        <p className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia nesciunt quae fuga, exercitationem veritatis enim sit aperiam eligendi, obcaecati qui repellat! Eius, soluta. Iste amet fugit consectetur, voluptatum tempore aliquam! uae fuga, exercitationem veritatis enim sit aperiam eligendi, obcaecati qui repellat! Eius, soluta. Iste amet fugit consectetur, voluptatum tempore aliquam! uae fuga, exercitationem veritatis enim sit aperiam eligendi, obcaecati qui repellat! Eius, soluta. Iste amet fugit consectetur, voluptatum tempore aliquam!</p>

        </div>
    
    <div className="col-start-2 block items-stretch justify-self-end">
       {
       Projects.map((item, key) => 
        <Project
        key={key}
        ProjectTitle={item.title}
        ProjectDescription={item.description}
        ProjectImg={item.img}
        ProjectLink={item.link}
        ProjectId={key} />
      )
    }
        </div>
       


    </div>
    </Container>


  );
}